### ISSUE TITLE
AJA_DISABLE_NVIDIA=ON does not disable rdmawhacker

### ISSUE THREAD

**Issue by tytan652** [aja-video/libajantv2#2]
Unlike other tools, rdmawhacker relies on CUDA but when `AJA_DISABLE_NVIDIA=ON` is set the tool is not skipped and CMake still tries to search for CUDA and add the target to build.

**Comment by thomas43** [comment]
Hi - do you have CUDA installed on your system? If not - the `rdmawhacker` target should not be added to your build. See `tools/rdmawhacker/CMakeLists.txt`: 
``` find_package(CUDA 11.1)
if (NOT CUDA_FOUND)
    message(STATUS "skipping rdmawhacker (CUDA not found)")
    return()
endif()
...
```

**Comment by tytan652** [comment]
> Hi - do you have CUDA installed on your system?

Installed or not is not the problem, the issue is that `AJA_DISABLE_NVIDIA` does not cover all the code using Nvidia.
It still try to check for CUDA, which if should not with `AJA_DISABLE_NVIDIA=ON`.

**Comment by paulh-aja** [comment]
We can make it bail out of the CMakeLists that look for CUDA if AJA_DISABLE_NVIDIA is set to ON. However ideally the check for CUDA should bail out on its own with no error. If the CUDA finder is currently throwing an error if CUDA is missing then we should fix that too.

**Comment by tytan652** [comment]
There is scenarios where someone wants to build a library without the support of another library even if the package is installed.

Here it would be building libajantv2 without Nvidia/CUDA even if it is installed, if I say to the build system to not build things related to Nvidia I assume it would avoid to search for CUDA.

**Comment by paulh-aja** [comment]
@tytan652 just wondering if you were able to test my fix?

**Comment by tytan652** [comment]
Fixed on main branch
