### ISSUE TITLE
Linux 6.10 kernel driver compile error

### ISSUE THREAD

**Issue by crosscoder1** [aja-video/libajantv2#26]
Linux 6.10.4 with latest git.

Since Linux 6.10, libajantv2 fails to compile due the transition from circ_buf to kfifo.  

See kernel commit : https://github.com/torvalds/linux/commit/1788cf6a91d9fa9aa61fc2917afe192c23d67f6a

Compile log : https://pastebin.com/9KdaXBgi

I was able to patch ntv2serial.c myself to get it to compile but I'm quite sure it can be done in a better way by someone more skilled.

**Comment by seanblit** [comment]
@crosscoder1 Thanks for the report, we have already taken care of this issue in our main branch with commits: 255e50ac217b4f927fc7a7ab3582692abebc2d5e and b7ecebb1c9b9ab82739e353ceaa4b822b13e6353.

For now until then next release you can try applying those same changes to whatever branch you are working on.
