### ISSUE TITLE
[issue] can't clone aja-video/mbedtls in build process

### ISSUE THREAD

**Issue by LunasShade** [aja-video/libajantv2#31]
libajantv2 is trying to clone mbedtls inside the build process but it didnt work.

to get around the error, i tried building mbedtls before libajantv2 as a normal module in my yaml and it gets cloned and built correctly. unfortunately libajantv2 doesn't seem to recognize that it's there, so it doesn't need to do that separately.

but it seems to be somehow due to the build process of libajantv2, as you can clone and build mbedtls both manually and as a module.

Error:
```
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /run/build/libajantv2/_flatpak_build
[  1%] Creating directories for 'mbedtls'
[  2%] Performing download step (git clone) for 'mbedtls'
Cloning into 'mbedtls'...
fatal: unable to access 'https://github.com/aja-video/mbedtls.git/': Could not resolve host: github.com
Cloning into 'mbedtls'...
fatal: unable to access 'https://github.com/aja-video/mbedtls.git/': Could not resolve host: github.com
Cloning into 'mbedtls'...
fatal: unable to access 'https://github.com/aja-video/mbedtls.git/': Could not resolve host: github.com
-- Had to git clone more than once: 3 times.
CMake Error at /run/build/libajantv2/_flatpak_build/ajantv2/mbedtls-prefix/tmp/mbedtls-gitclone.cmake:39 (message):
  Failed to clone repository: 'https://github.com/aja-video/mbedtls.git'


make[2]: *** [ajantv2/CMakeFiles/mbedtls.dir/build.make:97: ajantv2/mbedtls-prefix/src/mbedtls-stamp/mbedtls-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:720: ajantv2/CMakeFiles/mbedtls.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Error: module libajantv2: Child process exited with code 2
```

**Comment by thomas43** [comment]
Hi @LunasShade, I know that we've seen issues with GitHub dropping connection while cloning/updating submodules. This seems like your machine doesn't have a network connection to GitHub, which seems odd... 

Do you need to build with the plugin load capability? If so, `mbedtls` will need to be cloned? If not, you can just set the option `AJANTV2_DISABLE_PLUGIN_LOAD=ON`. 

See:
https://github.com/aja-video/libajantv2/blob/release/CMakeLists.txt#L41C8-L41C35
https://github.com/aja-video/libajantv2/blob/main/README.md#building-libajantv2

Note; We've updated the readme regarding this particular library in `main`, but not in the `release` branch. My apologies.

**Comment by LunasShade** [comment]
looks like everything is working for now, thanks. if there's anything else i'll let you know :)
