### ISSUE TITLE
ntv2version.h.in is installed in the include folder

### ISSUE THREAD

**Issue by tytan652** [aja-video/libajantv2#7]
The ntv2version.h.in is installed in the include folder (e.g. `/usr/include`), it should not be there since it is only meant to configure ntv2version.h for the library.

Edit: The file ends up with this path `/usr/include/libajantv2/ajantv2/includes/ntv2version.h.in`

**Comment by paulh-aja** [comment]
@thomas43 Do we use this in our internal OEM SDK build or is it no longer useful?

**Comment by thomas43** [comment]
@paulh-aja it is not used there, and is no longer useful. We will remove it.

**Comment by paulh-aja** [comment]
This is resolved by https://github.com/aja-video/libajantv2/commit/eb53f4b415b30bf8314d4abcbc373fef990d8a01.
